Added CUDA and forward refactor
Sergio-P/DSGD pull request #3
Opened 2022-07-29 07:31 UTC by LucasOyarzun

- Se añade CUDA al pasar todos los Tensor de pytorch a gpu, si el usuario tiene una gpu compatible y ha descargado e instalado los programas requeridos (Los de la tarjeta gráfica y los de CUDA como tal).
- Esta mejora solo se hace en DSClassifierMultiQ y DSModelMultiQ, pero se podría agregar al resto de clases (Hay que tener cuidado porque no todos los tensores se pueden pasar a gpu y algunos hay que devolverlos a cpu para ciertas operaciones).
- Se agregan los cambios de la rama forward_refactor, arreglando el problema del 1e-16 con la solución de Vicente, pero bien ejecutada (Línea 71).
- Se agregan requirements.txt, donde se incluyen las librerías de CUDA necesarias para usarlo, (torch, torchaudio y torchvision).

Con estos cambios el modelo pasó de ejecutarse en un dataset de 1300 filas durante 665 segundos a solo 11 segundos.

2022-07-29 15:42 UTC, Sergio-P requested changes
A modo general parece estar bastante bien. Se agregan algunos comentarios para mejorar la implementación y otros que son más decisiones de diseño que deberiamos convenir.

Como esta en los comentarios sería bueno dejar el device generico porque asi yo podria probarlo usando MSP en vez de cuda.

2022-07-29 15:42 UTC, Sergio-P commented on dsgd/DSClassifierMultiQ.py
> +device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
Creo que el device deberia ser un atributo de la clase, y quizas se podria pasar como parametro el device a usar. Por si algun ejemplo no funcionara en gpu, igual tener la posibilidad de volver a cpu. Esto además permitiría usar otros devices como MSP

2022-07-29 15:42 UTC, Sergio-P commented on dsgd/DSModelMultiQ.py
> +device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
Lo mismo que arriba, mejor que sea una tributo de la clase

2022-07-29 15:42 UTC, Sergio-P commented on dsgd/DSModelMultiQ.py
> +        ms = torch.stack(self._params).to(device)
Un problema que tiene forzar a usar siempre el precompute rules es que se usa una matriz de tamaño (numero de reglas) x (numero de instancias) esto podria usar mucha RAM si esos numero son grandes. Se deberia tener un flag igual para activar o desactivar este comportamiento como se hace ahora

2022-07-31 13:01 UTC, LucasOyarzun commented
Ahí hice los cambios para poder elegir el device y no supe como ponerle a lo de Vicente asi que le puse force_precompute, también quedó como opcional, por defecto ambos quedaron sin los cambios nuevos.

2022-07-31 15:48 UTC, Sergio-P requested changes
OK ahora se ve bastante mejor. Para terminar los últimos detalles creo que falta lo siguiente:
- Agregar al README.md la descripción de los dos nuevos atributos
- Agregar en la carpeta examples, un ejemplo de uso del modelo con gpu para algún dataset (o cpu vs gpu)
- Yo voy a probar si hay que hacer algún cambio extra para que el modelo funcione con MPS

2022-08-09 06:39 UTC, LucasOyarzun commented
- Se añadieron los parámetros nuevos al README.
- Se corrigió el requirements.txt para poder instalar las librerías de pytorch con CUDA.
- Se Agrega un ejemplo comparando los tiempos de ejecución.

Imagen del ejemplo de comparación de tiempos de ejecución:

![image](https://user-images.githubusercontent.com/62770158/183581130-335e8b82-62ec-446f-9725-27bf4f087a50.png)

2022-08-10 20:52 UTC, Sergio-P approved these changes

2022-08-10 20:52 UTC, merged